### PR TITLE
Allow applying dimensions through WMS FILTER parameter

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Requires https://github.com/camptocamp/tilecloud/pull/214 and https://github.com/mapserver/mapcache/pull/185

### CODE REVIEW

**Comment by pvalsecc** [comment]
@arnaud-morvan, what's up with this 1 year old PR?

**Comment by arnaud-morvan** [comment]
Waiting for mapserver/mapcache#185 which has no response from committers since 1 year.

**Comment by pvalsecc** [comment]
Indeed.

**Comment by sbrunner** [comment]
Shouldn't we close this pull request?

**Comment by arnaud-morvan** [comment]
Seems that we've got a response from the MapCache reviewers on 7 feb (more than 18 months after PR).
We should be able to revive this, but QGIS server seems to support dimensions now, this might not be needed anymore.

**Comment by sbrunner** [comment]
OK => close

**Pull request closed without merging**
